name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@1e60f620b9541d910a34ff8987c4e60f18f47259 # v4.1.3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run lint
      - run: npm run test
